### ISSUE TITLE
Largest Contentful Paint element Error!

### ISSUE THREAD

**Issue by zhouguomai** [GoogleChrome/developer.chrome.com#6327] opened 2023-05-16 00:56 UTC
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/71681451/d48ba9b3-d26f-472d-b8a2-7d9a8dca8e6d)
![image](https://github.com/GoogleChrome/developer.chrome.com/assets/71681451/55079761-b651-4f0b-a0db-9550ae70f336)
Largest Contentful Paint element Error!

**Comment by DaveSkender** [comment] 2023-05-16 04:27
Duplicate of https://github.com/GoogleChrome/lighthouse/issues/15075

**Closed** 2023-05-16 08:22 UTC
Labels: bug, P2
