### ISSUE TITLE
ExtensionPanel.onSearch.addListener's callback isn't elaborated enough

### ISSUE THREAD

**Issue by Yash-Singh1** [GoogleChrome/developer.chrome.com#120] opened 2020-12-21 05:35 UTC
**Describe the bug**

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/reference/devtools_panels/#:~:text=onSearch
2. The arguments for the callback aren't elaborated

**Expected behavior**

Better explanation of arguments

**Screenshots**

![Screenshot from 2020-12-20 21-27-42](https://user-images.githubusercontent.com/53054099/102742985-3c483b00-430b-11eb-9ca3-902763193bf9.png)

See: https://stackoverflow.com/a/43116148/13514657

**Comment by samthor** [comment] 2021-01-05 01:50
cc @karan173 this seems like something we could fix in the underlying JSON/IDLs.

**Comment by karan173** [comment] 2021-01-06 14:35
IIUC the issue is that the possible values for the "action" key aren't described clearly. I've opened a new issue at https://bugs.chromium.org/p/chromium/issues/detail?id=1163519 to track this; closing this one.

**Closed by karan173** 2021-01-06 14:35 UTC
Labels: bug
