### ISSUE TITLE
Tabs widget like web.dev has

### ISSUE THREAD

**Issue by awfuchs** [GoogleChrome/developer.chrome.com#553] opened 2021-03-23 21:32 UTC
It would be useful to have a tabs widget (like the one in web.dev) to compare multiple code versions, approaches, languages, etc... This has come up a couple of times:

* For comparing MV2 to MV3 docs
* For comparing callback to promise implementations

And it's sure to be useful many more places too.

**Comment by robdodson** [comment] 2021-03-23 21:35
Dupe of #90

**Closed by robdodson** 2021-03-23 21:35 UTC
Labels: feature request
