### ISSUE TITLE
Broken link to extensions/reference/windows/#current-window

### ISSUE THREAD

**Issue by johnmellor** [GoogleChrome/developer.chrome.com#5398] opened 2023-02-22 01:54 UTC
**Describe the bug**
Broken link in documentation. https://developer.chrome.com/docs/extensions/reference/windows/#method-getCurrent and https://developer.chrome.com/docs/extensions/reference/windows/#property-WINDOW_ID_CURRENT both link to https://developer.chrome.com/docs/extensions/reference/windows/#current-window which does not exist.

**Expected behavior**
Either:
a) they should link to https://developer.chrome.com/docs/extensions/reference/windows/#the-current-window instead;
or:
b) #the-current-window should be renamed back to #current-window

**Comment by dstmarthe** [comment] 2023-11-10 05:49
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. A duplicate of this issue (I transferred it from here before seeing this one.) has been made at our new issue tracker. https://issuetracker.google.com/issues/309981771

**Closed by dstmarthe** 2023-11-10 05:49 UTC
Labels: bug, P2, extensions, extensions-reference
