### ISSUE TITLE
Please adhere to autocomplete="off"

### ISSUE THREAD

**Issue by SDAdham** [GoogleChrome/developer.chrome.com#2538] opened 2022-04-05 12:14 UTC
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

Dear Chrome team, we are suffering due to the inability of chrome to respect and adhere to `autocomplete="off"`. Based on our research, we understand that Chrome team is trying to handle the abuse of websites forcing the autocomplete to off, but that's definitely is for reason unless they have bad developing experience and causing bad user-experience for their websites BUT that would be their issue not Chrome's.

**To Reproduce**

We tried (some of the suggestions from below may work but not forever, it's just few refreshes, or going back to the page, we see the autocomplete is back on and remembering input is still being prompt):
- `autocomplete="off"`
- `autocomplete="wafowifh134e19487"`
- `autocomplete="platform-fieldname"`
- The wrapping form with `autocomplete="off"`

In our product, we let our users to save their customers information, it is by any means that they are not supposed to save customer information on their browser history for security reasons.

**Expected behavior**

Easy, please adhere to `autocomplete="off"` and if provided, remember the autocomplete value.

**Screenshots**

Here is an example page where we are suffering from:
![image](https://user-images.githubusercontent.com/11182824/161750422-ced1cde8-ccfc-4a1b-b370-d52bf7af5e81.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux - openSUSE Tumbleweed
 - Browser [e.g. chrome, safari] chrome - Version 100.0.4896.75 (Official Build) (64-bit)
 - Version [e.g. 22] Version 100.0.4896.75 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

Please by all means, adhere to autocomplete requests, it's not google's chrome responsibility to fix what other bad website developers are doing wrong in terms of abusing the autocomplete feature.

**Comment by SDAdham** [comment] 2022-04-05 12:23
Here is a reference to Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=370363#c7
Suggestions:
- https://gist.github.com/niksumeiko/360164708c3b326bd1c8
- https://stackoverflow.com/questions/2530/how-do-you-disable-browser-autocomplete-on-web-form-field-input-tags
- https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

**Comment by SDAdham** [comment] 2022-04-05 12:31
https://bugs.chromium.org/p/chromium/issues/detail?id=587466

**Comment by jeffposnick** [comment] 2022-04-05 13:10
The Chromium bugs that have been filed are the correct way to keep track of this issue, and to hear feedback from the teams responsible. I'm closing this issue as we use this repo to track content issues with the https://developer.chrome.com/ website.

**Closed as completed by jeffposnick** 2022-04-05 13:10 UTC
Labels: bug, P2

**Comment by SDAdham** [comment] 2022-04-05 13:38
Hello @jeffposnick , how is my comment will make a difference in over 580 comments issue here at https://bugs.chromium.org/p/chromium/issues/detail?id=587466 ?

**Comment by alxndr-w** [comment] 2023-09-08 13:57
While Chromium bugs might be the correct way to keep track of this issue, it seems worthwhile to annoy more people to address this issue. Because another year passed by and last time I checked it: Google Chrome developers will feel responsible for any damage caused by this bug, like it happened to my client (and their clients).
