### ISSUE TITLE
Missing image from blog post

### ISSUE THREAD

**Issue by chrishtr** [GoogleChrome/developer.chrome.com#4065] opened 2022-10-20 01:24 UTC
https://developer.chrome.com/articles/renderingng-data-structures/

Has a link to the "immutable fragment tree" image ([url](https://wd.imgix.net/image/HodOHWjMnbNw56hvNASHWSgZyAf2/EmO3PAWQ6QzMgwJweFvl.jpeg?auto=format&w=964))

It used to work but now shows a blank image. Can you please fix it?

@una can you repost the original image in case it's needed?

**Comment by rachelandrew** [comment] 2022-10-20 02:29
@chrishtr that's odd, some of the images in the `srcset` attribute are loading blank, the main image is fine https://wd.imgix.net/image/HodOHWjMnbNw56hvNASHWSgZyAf2/EmO3PAWQ6QzMgwJweFvl.jpeg?auto=format

@devnook any ideas what is happening here? I can reupload the image, but it seems odd we have a bunch of blank images.

**Comment by chrishtr** [comment] 2022-10-27 03:55
Hi any update?

**Comment by AaronForinton** [comment] 2022-11-12 03:41
Hi @chrishtr. I can't replicate this issue. I'm assuming it has been fixed by some dependency or other somewhere in the meantime - can you confirm the same?

**Comment by chrishtr** [comment] 2022-11-20 19:57
It does seem like most are fixed. I still found one broken image in [this post](https://developer.chrome.com/articles/renderingng-architecture/):

https://wd.imgix.net/image/ZDZVuXt6QqfXtxkpXcPGfnygYjd2/RKXD237nuR9aHxw6O2Mc.jpeg?auto=format&w=964

(shows a blank gray rectangle for me)

Also, this one is corrupted?

https://wd.imgix.net/image/ZDZVuXt6QqfXtxkpXcPGfnygYjd2/5pqtEVTK9xbbB7sc2s87.jpeg?auto=format&w=964

**Comment by matthiasrohmer** [comment] 2022-11-21 08:34
Probably an AVIF encoding issue on imgix. Hardcoding the `format` query parameter to another format or loading the image in a browser that doesn't support AVIF works for me:

- format=auto, not working in Chrome, serving AVIF: https://wd.imgix.net/image/ZDZVuXt6QqfXtxkpXcPGfnygYjd2/RKXD237nuR9aHxw6O2Mc.jpeg?auto=format&w=964
- format=wepb, serving WEBP: https://wd.imgix.net/image/ZDZVuXt6QqfXtxkpXcPGfnygYjd2/RKXD237nuR9aHxw6O2Mc.jpeg?auto=webp&w=964
- format=png, serving PNG: https://wd.imgix.net/image/ZDZVuXt6QqfXtxkpXcPGfnygYjd2/RKXD237nuR9aHxw6O2Mc.jpeg?auto=png&w=964

**Comment by matthiasrohmer** [comment] 2022-11-21 09:53
@devnook just verified it is an imgix issue that has been reported with them. Let us collect occurrences here to forward to imgix for them to debug as they couldn't reproduce it yet.

**Comment by chrishtr** [comment] 2022-11-23 17:51
Should we just change them to png for now? Does imgix plan to have have a fix soon?

**Comment by chrishtr** [comment] 2023-01-12 18:16
Friendly ping on this - were the issues fixed in imgix?

**Comment by rachelandrew** [comment] 2023-01-12 18:21
I don't know about imgix but I believe we sorted the images by reuploading them, are you still seeing an issue as they look fine for me.

@matthiasrohmer do you know anything further on the initial issue, as I'm somewhat concerned other articles will have the same problem, and it's not easy to spot as it happens only at some breakpoints.

**Comment by matthiasrohmer** [comment] 2023-01-12 19:15
Thanks for the ping!

Unfortunately we weren't able to shine more light on this. When @devnook tried to investigate with imgix they were saying it's an isolated, non-reproducible issue.

Something we could do is writing a quick crawler that tries to download all images we have on the site as AVIFs (as those seem the ones to be failing) and checks if they are broken. That might show some more instances for imgix engs to derive an issue pattern. What do you all think?

**Comment by matthiasrohmer** [comment] 2023-07-31 08:22
Won't fix, due to the pending move to the new CMS.

**Closed by matthiasrohmer** 2023-07-31 08:22 UTC
Labels: bug, P2, content
