### ISSUE TITLE
Chrome Extension store API instructions are outdated

### ISSUE THREAD

**Issue by ggaabe** [GoogleChrome/developer.chrome.com#4229] opened 2022-11-07 23:00 UTC
**Describe the bug**
The API instructions point to using an out-of-band api for retrieving an access token. OOB is deprecated and unusable now for new users.
The document here points users to entering a URL with the `oob` flag in the URL:
https://github.com/GoogleChrome/developer.chrome.com//blob/main/site/en/docs/webstore/using_webstore_api/index.md

Under "Testing your OAuth application".

**To Reproduce**
1. Go to the [Testing Your OAuth application section of the chrome store API](https://github.com/GoogleChrome/developer.chrome.com//blob/main/site/en/docs/webstore/using_webstore_api/index.md)
2. Enter the URL with relevant credentials
3. See error

**Expected behavior**
An access token should be provided. Instead there is a deprecation error. The current instructions should be updated to reflect this reality.

**Comment by sfoslund** [comment] 2022-12-06 16:47
@AmySteam what are the updated instructions going to be? I am running into this issue and unsure of how to work around it.

**Comment by mariuszste** [comment] 2022-12-21 13:48
> what are the updated instructions going to be? I am running into this issue and unsure of how to work around it.

The simplest workaround is to just put something fake like `http://localhost:1234/whatever` in the `redirect_uri` fields and after you log in then just grab the code from the address bar in your browser when it tries to open the non-existent url. you can then exchange it for a token using the same endpoint as before, you just have to swap `redirect_uri` to the one you use before.

**Comment by mormubis** [comment] 2023-02-17 20:20
Do you happen to have any updates on this? Can you replace OAuth with API Key to avoid these strange use cases?

**Comment by dstmarthe** [comment] 2023-11-15 00:16
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at: https://buganizer.corp.google.com/issues/311045658

**Comment by oliverdunk** [comment] 2024-01-08 10:07
Thanks for filing this. This is definitely one we are overdue to fix but we already have https://github.com/GoogleChrome/developer.chrome.com/issues/3699, so closing as a duplicate of that.

**Closed by oliverdunk** 2024-01-08 10:07 UTC
Labels: bug, P2, extensions, content update, transferred
