### ISSUE TITLE
Documentation for extensions manifest v3 docs for CSP is missing.

### ISSUE THREAD

**Issue by naskooskov** [GoogleChrome/developer.chrome.com#3516] opened 2022-08-22 17:48 UTC
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**
A few pages on the site link to CSP documentation at https://developer.chrome.com/docs/extensions/mv3/contentSecurityPolicy/. This URL leads to Aw Snap page.

**To Reproduce**
1. Go to 'https://developer.chrome.com/docs/extensions/mv3/sandboxingEval/'
2. Click on ' Content Security Policy (CSP)' in the first sentence of the article.
3. See error

**Expected behavior**
Get to the CSP documentation.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 106.0.5231.2

**Additional context**
There are other pages that I don't recall that have the same link, all of them leading to this error page.

**Comment by jpmedley** [comment] 2022-10-20 19:22
This is a duplicate of at least one other open ticket. Plus I'm consolidating all the missing manifest members under #163.

**Closed by jpmedley** 2022-10-20 19:22 UTC
Labels: bug, P2, extensions, content
