### ISSUE TITLE
Difference JavaScript output between browser and NodeJs

### ISSUE THREAD

**Issue by Jrejoire** [GoogleChrome/developer.chrome.com#4058] opened 2022-10-19 11:15 UTC
**Bug**
Here is the code causing problems:
```
const updateObject = () => {
    let object = {
        key: {
            entry: "initialValue",
        }
    }

    console.log(object);
    console.log(object.key);

    object.key.entry = "newValue";
}

updateObject();

//returns
//{"key": {"entry": "newValue" }}
//then returns
//{"entry": "initialValue"}
```

This happens when running this code in the browser but not on a NodeJs script.
I spent a full day to understand what was going on. Was difficult to debug as the issue was actually from some code after the logs were displayed. 

**To Reproduce**
![image](https://user-images.githubusercontent.com/33304306/196674396-e76be82d-26de-46c5-8eda-5697e9e70e4a.png)
As shown in the screenshot, you can simply copy this code into the browser and see the incorrect logs.

**Expected behavior**
The expected behavior should be like in Node.js:
```
{ array: [ { key: 'firstValue' } ] }
[ { key: 'firstValue' } ]
```
![image](https://user-images.githubusercontent.com/33304306/196675978-9c7da2be-efaf-4f81-9bb3-2230952bd68f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 106.0.5249.119

**Comment by guest271314** [comment] 2022-10-24 00:53
`{entry: 'initialValue'}` is displayed until the object in spected window is expanded.

**Comment by rachelandrew** [comment] 2022-10-24 05:35
@Jrejoire is this an example you found in an article on this site?

**Comment by Jrejoire** [comment] 2022-10-25 07:53
> const updateObject = () => {
>     let object = {
>         key: {
>             entry: "initialValue",
>         }
>     }
> 
>     console.log(object);
>     console.log(object.key);
> 
>     object.key.entry = "newValue";
> }
> 
> updateObject();

Yes that's correct. Thanks for pointing that out.
![image](https://user-images.githubusercontent.com/33304306/197715280-8e5af848-01bd-4534-aecb-4598b811855a.png)

@rachelandrew The example is from me. I replicated a simple version of the issue in the browser.

**Comment by tophf** [comment] 2022-10-26 09:07
FWIW, this is how devtools console always behave. Think of the console as of a historical log, not a live object.

**Comment by guest271314** [comment] 2022-10-26 23:12
@tophf Re https://github.com/w3c/webextensions/issues/293

> This workaround is fragile because the web page can delete the iframe, even if we hide it inside shadow DOM.

Have you ever actually encountered that occurring in practice? Asking you here because W3C banned me.

**Comment by tophf** [comment] 2022-10-26 23:23
No, I haven't, but I know there are sites that pro-actively fight extensions.

**Comment by guest271314** [comment] 2022-10-26 23:58
I have run this code https://github.com/guest271314/captureSystemAudio/blob/master/native_messaging/capture_system_audio/transferableStream.js thousands of times on arbitrary Web sites, transfering substantial data between an appended `<iframe>` with with `src` set to the extension URL set with `"web_accessible_resources"` defined in manifest.json using Transferable Streams. I have never encountered a Web site removing the embedded `iframe`.

**Comment by guest271314** [comment] 2022-10-27 00:31
@tophf I have kept MV3 `ServiceWorker` active well over 24 hours - passing messages between an embedded `<iframe>` and the `ServiceWorker` and the arbitrary Web site using this approach https://github.com/guest271314/persistent-serviceworker/tree/main/chromium_extension_web_accessible_resources_iframe_message_event.

**Comment by tophf** [comment] 2022-10-27 09:00
I'm not saying there's a lot of such sites. You or I may never encounter one in our entire live.

**Comment by tophf** [comment] 2022-10-27 14:00
"impossible" is a part of a phrase which says that it is impossible to do both "directly && instantly". Directly in this context means an API that can be used inside the content script without the need to create an intermediate entity that can be seen or even removed by a hostile web site or another extension.

**Comment by guest271314** [comment] 2022-10-27 14:08
> without the need to create an intermediate entity that can be seen or even removed by a hostile web site or another extension.

We have already established that never happens in practice.

**Comment by tophf** [comment] 2022-10-27 14:13
Just because it doesn't happen in your practice or mine or for 99.999999999% use cases doesn't mean its reliable, just like solid glass is inherently fragile even though it doesn't break usually.

**Comment by guest271314** [comment] 2022-10-27 14:16
You have to produce empirical evidence that your claim happens at all. Right now it is just a claim without evidence.

Nothing breaks here https://github.com/guest271314/persistent-serviceworker/. You can keep the MV3 `ServiceWorker` active indefinitely and send whatever messages you want to and fro.

For direct communication you can use `"externally_connectable"` to connect directly from the arbitrary Web page.

**Comment by tophf** [comment] 2022-10-27 14:19
A DOM element can be trivially removed, that's not something that needs an evidence. It means that using an iframe is dependent on the goodwill of the web site and other extensions. It is what I called fragile as opposed to something unbreakable like an internal API not exposed via DOM.

**Comment by guest271314** [comment] 2022-10-27 14:20
On what specific Web site does that happen? 

Have you tried using `"externally_connectable"`? That is direct comunication between the arbitrary Web site and `ServiceWorker`.

**Comment by guest271314** [comment] 2022-10-27 14:22
@tophf You need to cite and produce at least one (1) example of a Web site removing an `iframe` appended to the `focument` after the page loads. Otherwise your claims lack proof.

**Comment by tophf** [comment] 2022-10-27 14:28
I don't need to produce any evidence to say that removing a DOM element is possible and hence anything based on that is fragile. I also don't need to convince you hijacking an unrelated issue.

**Comment by guest271314** [comment] 2022-10-27 14:30
I was just trying to convey to you the requirement you have is possible. So far you have not produced any evidence that Web site arbitrarily remove `iframe`s appended to the `document`.

I suggest you look into `"externally_connectable"` which does not require an `iframe` at all.

**Comment by tophf** [comment] 2022-10-27 14:33
I already know it is possible, no need to convince me :-) As for externally_connectable it won't help to transfer data from the background script to the content script. I guess the title of my issue confusingly mentions "web pages", which I'll fix now.

**Comment by tophf** [comment] 2022-10-27 14:48
There are many uses for a content script. As for my claim that a site can trivially remove a DOM element, if something is possible I won't pretend that just because I've never seen it happen myself then it can never happen in real life. I do agree that there's a high probability that you'll never encounter such a site in your practice especially if your extension doesn't do things that the web site owners might dislike.

**Comment by guest271314** [comment] 2022-10-27 23:33
@tophf 

Chrome tab on update execute script is content script equivalent. I think you should experiment with `"externally_connectable"` https://github.com/guest271314/persistent-serviceworker/blob/main/chromium_extension_externally_connectable/background.js for direct connection to MV3 `ServiceWorker` from Web sites you want to connect to from. Then no `iframe` is involved. 

```
async function persistentExternalConnection(id) {
  if (!self.externalPort) {
    function handleMessage(e) {
      console.log(e);
    }
    function handleDisconnect(resolve) {
      self.externalPort.onMessage.removeListener(handleMessage);
      self.externalPort.onDisconnect.removeListener(handleDisconnect);
      self.externalPort = null;
      resolve();
    }
    async function* active(id) {
      while (true) {
        yield new Promise((resolve) => {
          self.externalPort = chrome.runtime.connect(id, {
            name: 'active',
          });
          self.externalPort.onMessage.addListener(handleMessage);
          self.externalPort.onDisconnect.addListener(
            handleDisconnect.bind(null, resolve)
          );
        });
      }
    }
    async function stream() {
      for await (const _ of active(id)) {
      }
    }
    stream();
  } else {
    self.externalPort.disconnect();
    self.externalPort = null;
  }
}

chrome.action.onClicked.addListener(async (tab) => {
  // TODO: Dynamically update "externally_connectable" in manifest.json
  chrome.scripting.executeScript({
    target: {
      tabId: tab.id,
    },
    world: 'MAIN',
    args: [chrome.runtime.id],
    func: persistentExternalConnection,
  });
});
```

**Comment by tophf** [comment] 2022-10-28 07:15
Thanks, I don't need it for this task because extension messaging can't transfer huge data instantly, which was the entire point of the issue we are discussing.

**Comment by guest271314** [comment] 2022-10-28 08:05
> I don't need it for this task because extension messaging can't transfer huge data instantly

Yes, it can. Several ways. You can use Transferable Streams, `WebAssembly.Memory`, etc.

I document use content scripts in my code.

**Comment by tophf** [comment] 2022-10-28 08:40
Extension messaging is what I call chrome.runtime messaging and it can only transfer JSON-compatible types due to internal use of JSON.stringify.

**Comment by guest271314** [comment] 2022-10-29 00:09
It is a simple matter to stream JSON.

It is possible to create a `MessageChannel` in MV3 `ServiceWorker` and transfer one of the paired `MessagePort`s to arbitrary Web pages.

I think we should continue this discussion over here https://github.com/GoogleChrome/chrome-extensions-samples/issues/766.

**Comment by tophf** [comment] 2022-10-29 08:05
Anything JSON-based is absolutely uninteresting in the context of the issue we are discussing.

A port idea is better but to transfer the port from extension SW to a web page you would need to create an iframe inside the web page anyway even if you remove it immediately. This is still fragile in the same sense that a hostile site can detect it and remove (unless you go through the pains of cloaking all the relevant DOM accessors) and still incurs the overhead to create/initialize the frame environment (50ms+), but less fragile than keeping the iframe for an extended amount of time.

**Comment by guest271314** [comment] 2022-10-29 12:50
> Anything JSON-based is absolutely uninteresting in the context of the https://github.com/w3c/webextensions/issues/293.

No, it is not. JSON can be streamed. You can't tell the difference between a JSON stream and a non-JSON stream re passing a substantial quantity of data.

> This is still fragile in the same sense that a hostile site can detect it and remove

We have already established you cannot demonsrate that ever happening in practice.

**Comment by tophf** [comment] 2022-10-29 12:54
The issue is about instant transfer, so anything JSON-based is out of the question. And there's no need to demonstrate that a DOM element can be removed, it's just a given.

**Comment by guest271314** [comment] 2022-10-29 13:01
> The issue is about instant transfer, so anything JSON-based is out of the question.

Yet you erroneous claimed `Blob`s are transferable, which they are not.

What precisley are you trying to transfer?

> And there's no need to demonstrate that a DOM element can be removed, it's just a given.

No, nothing is a given.

You need to post steps to reproduce, which you haven't.

**Comment by tophf** [comment] 2022-10-29 13:07
1. Blob's data is transferable, which is the only thing that matters. The Blob itself is a tiny wrapper over the data that is instantly transferable.
2. Any big binary data
3. element.remove()

**Comment by guest271314** [comment] 2022-10-29 13:09
No, `Blob` data is not transferable. A `Blob` is not a transferable object.

On what specific Web site have you encountered an `iframe` with `src` set to a Chrome extension URL being removed?

**Comment by tophf** [comment] 2022-10-29 13:11
Blob's arrayBuffer data is transferable, which can be trivially verified by using performance timing. 
I don't have a URL.

**Comment by guest271314** [comment] 2022-10-29 13:14
The `Blob` is not transferable, period https://plnkr.co/edit/ZyutxttrhgerqZpk?open=lib%2Fscript.js.

**Comment by tophf** [comment] 2022-10-29 13:16
Your demo prints the blob in console, just as it should.

**Comment by guest271314** [comment] 2022-10-29 13:20
Yes, and notie the `size` of the `Blob` in Worker after `postMessage(blob, [await blob.arrayBuffer()]);`, `3`. indicating the `Blob` was **not** _transfered_. 

Remove 2d parameter we get the same result https://plnkr.co/edit/oDrKyzzknXkrVu9m?open=lib%2Fscript.js.

**Comment by guest271314** [comment] 2022-10-29 13:24
You are using the term "transferred" incorrectly in this context.

**Comment by tophf** [comment] 2022-10-29 13:29
Okay, I see now where I was wrong. Apparently the speed difference confused me. The Blob is sent instantly even without being actually transferred, whereas a string takes a lot of time probably due to the need to intern it in the receiver.

**Comment by guest271314** [comment] 2022-10-29 13:30
No. `Blob` construction is expensive. It is not sent _instantly_.

**Comment by tophf** [comment] 2022-10-29 13:32
I meant colloquially instant, compared the time spent in chrome.runtime messaging to send over the equal amount of data (1GB string split in 64MB chunks).

**Comment by guest271314** [comment] 2022-10-29 13:34
staWe're not dealing with colloquialisms. We are dealing with technical documents and claims that must be reproduced or rendered null and void based on the scientific method.

**Comment by tophf** [comment] 2022-10-29 13:35
We're dealing with an example for an issue, not with a scientific article. A few milliseconds to send 1GB may be considered instant in this context.

**Comment by guest271314** [comment] 2022-10-29 13:36
Alright, we have establish we can use `postMessage()` to send a copy of a `Blob` to a different browing context. 

That process does not occur "instantly".

Now, we can move on to the claim of Web sites removing `iframe`s, which I suspect you will have a serious issue reproducing.

**Comment by tophf** [comment] 2022-10-29 13:37
I don't need to reproduce the iframe problem to say it's possible, just like I don't need to break a glass to say it's fragile.

**Comment by guest271314** [comment] 2022-10-29 13:39
On what Web site does that happen?

Yes, you need to provide steps to reproduce and someone other than yourself needs to reproduce the claim. That's how the scientific method works.

> Now watch. ..., this how science works.
> One researcher comes up with a result.
> And that is not the truth. No, no.
> A scientific emergent truth is not the
> result of one experiment. What has to
> happen is somebody else has to verify
> it. Preferably a competitor. Preferably
> someone who doesn't want you to be correct.
> 
> - Neil deGrasse Tyson, May 3, 2017 at 92nd Street Y

**Comment by tophf** [comment] 2022-10-29 13:40
Gee, I'll never be a scientist, let's leave it at that.

**Comment by rachelandrew** [comment] 2022-10-29 15:42
I can't find anything in this exchange relating to an article on developer.chrome.com, therefore I'm closing the issue, as that's what this repo is for.

If this issue did indeed relate to an article or documentation on this site, can the OP please raise it again clearly pointing to the issue? Thanks!

**Closed by rachelandrew** 2022-10-29 15:42 UTC
Labels: bug, P2
