### ISSUE TITLE
Menu sidebar and the cookie bottom UI on Edge mobile 45

### ISSUE THREAD

**Issue by hwikyounglee** [GoogleChrome/developer.chrome.com#35] opened 2020-12-08 22:02 UTC
![Screenshot_20201208-135452](https://user-images.githubusercontent.com/7561395/101546553-cda7cc80-395d-11eb-84e4-aba2e302ed0d.png)
OK got it button is missing on Edge (right)
![Screenshot_20201208-135543](https://user-images.githubusercontent.com/7561395/101546556-d0a2bd00-395d-11eb-971c-572288542b99.png)
Edge version 45
![Screenshot_20201208-135505](https://user-images.githubusercontent.com/7561395/101546560-d39dad80-395d-11eb-9025-a2b3c39f1bde.png)
Side menubar is not opening on Edge (right)

**Comment by samthor** [comment] 2021-01-05 01:19
Seems like we need to install Edge on Mobile to see what is going on here.

**Comment by ericlaw1979** [comment] 2021-01-19 14:44
Edge Mobile is presently horribly outdated and based on Chromium 77. The console shows "Uncaught SyntaxError: Unexpected token ." but it unfortunately doesn't break down *where* the parsing of the script failed.

You don't even need Edge Mobile to test this, just pull an old Chrome Desktop build from developer.chrome.com. I repro'd in v78 (686186), for instance. The site works fine in Chrome 81.

**Comment by ericlaw1979** [comment] 2021-01-19 14:52
This was fixed in Chrome by this V8 Roll:
https://chromium.googlesource.com/v8/v8/+log/aadf1619..b3cc49df
which landed as 34ae61a8... initially landed in 80.0.3958.0.

Presumably, the issue is the lack of optional-chaining in earlier builds; we see ${this.blogResults?.length? in this code.

**Closed** 2021-01-22 18:32 UTC
Labels: P1, bug
