### ISSUE TITLE
Missing parts 

### ISSUE THREAD

**Issue by Ammar-Alkhaffaf** [GoogleChrome/developer.chrome.com#742] opened 2021-05-06 15:34 UTC
Please review the topic of (View and change CSS) on this webpage (https://developer.chrome.com/docs/devtools/css/) because the interactive parts are not exist, thanks

**Comment by robdodson** [comment] 2021-07-30 01:16
Duplicate of #606

**Closed by robdodson** 2021-07-30 01:16 UTC
Labels: bug
