### ISSUE TITLE
Broken links on Getting Started page for Chrome Extension docs

### ISSUE THREAD

**Issue by aschine** [GoogleChrome/developer.chrome.com#133] opened 2020-12-24 18:24 UTC
**Describe the bug**
On page: https://developer.chrome.com/docs/extensions/mv3/getstarted/
Several links to project assets are not functioning, across multiple browsers. Multiple links that claim to lead to assets are broken, listed below:

https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started_complete.zip
https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started/manifest.json
https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started/background.js
https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started/popup.html
https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started/images.zip
https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started/popup.js
https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started/options.html
https://developer.chrome.com/docs/extensions/mv3/getstarted/examples/tutorials/get_started/options.js

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 (19H2)
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (x86_64)

Screenshots of broken links attached
<img width="692" alt="developer_chrome_com" src="https://user-images.githubusercontent.com/24419411/103102716-490aae80-45eb-11eb-9d65-6c8b2dd56abf.png">
<img width="865" alt="404_-_Chrome_Developers_and_Inbox__2_627_messages__8_unread_" src="https://user-images.githubusercontent.com/24419411/103102722-4f992600-45eb-11eb-8300-83d73bad3d86.png">

**Comment by avm99963** [comment] 2020-12-25 11:20
Thanks for reporting! This seems like a duplicate of #60.

**Comment by raghibhuda** [comment] 2020-12-30 06:15
Facing the same issue

**Comment by LordNoteworthy** [comment] 2021-01-15 01:32
Same here.

**Closed** 2021-01-27 18:16 UTC
Labels: bug
