### ISSUE TITLE
Description for `chrome.browserAction` redirects to `#popups` instead of `#popup`

### ISSUE THREAD

**Issue by Yash-Singh1** [GoogleChrome/developer.chrome.com#1475] opened 2021-09-21 01:10 UTC
⚠️ This is for issues with the https://developer.chrome.com site, not Chromium itself.
If you want to file a bug with Chromium (the open-source project behind Google Chrome and other browsers), please use https://crbug.com.

**Describe the bug**

**To Reproduce**
1. Go to https://developer.chrome.com/docs/extensions/reference/browserAction
2. Click on `popup` link in description
3. Notice that the hash in the URL is `popups` and the page doesn't scroll to the `Popup` heading

**Expected behavior**

Scrolls down to `Popup` heading

**Screenshots**

![Screenshot from 2021-09-20 18-08-29](https://user-images.githubusercontent.com/53054099/134097317-54cc6f19-8810-4aa4-99b9-3d77bb03ca1e.png)
![Screenshot from 2021-09-20 18-08-33](https://user-images.githubusercontent.com/53054099/134097318-79a181da-237c-4230-90fc-901a42ed8341.png)

**Comment by tannerdolby** [comment] 2021-09-21 05:22
I think the "Description" text is being generated from `{{ namespace.description | md | safe }}` within [`namespace-reference.njk`](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/_includes/layouts/namespace-reference.njk#L67-L72).

Therefore the `href` for that `<a href="#popups">` element is not present in the [`/references/browserAction/index.md`](https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/en/docs/extensions/reference/browserAction/index.md) template.

So I think however each UI part (icon, tooltip, badge, popup) is getting highlighted and turned into a link is where `<a href="#popups">` is happening instead of `href="#popup"` which links to the correct "Popup" section as intended. I tried figuring out if `md` was making the links within the `namespace.description` or if it was a shortcode or filter, or global data file but I couldn't find exactly where the links were being created.

cc @samthor

**Comment by dstmarthe** [comment] 2023-11-23 05:02
Thanks for raising this. It should be pretty easy to fix. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/issues/312790951

**Closed by dstmarthe** 2023-11-23 05:02 UTC
Labels: bug, P2, extensions, content, extensions-reference
