### ISSUE TITLE
Broken links on the "Extending DevTools" page

### ISSUE THREAD

**Issue by OrKoN** [GoogleChrome/developer.chrome.com#2417] opened 2022-03-25 09:28 UTC
There are a few broken links on this page: 

1. [featured DevTools extensions](https://developer.chrome.com/docs/devtools/docs/extensions-gallery/)
2. [devtools.inspectedWindow](https://developer.chrome.com/docs/extensions/mv3/devtools.inspectedWindow)
3. [devtools.network](https://developer.chrome.com/docs/extensions/mv3/devtools.network)
4. [devtools.panels](https://developer.chrome.com/docs/extensions/mv3/devtools.panels)
5. [extension](https://developer.chrome.com/docs/extensions/extension/) and [runtime](https://developer.chrome.com/docs/extensions/runtime/) APIs
6. [scripting.executeScript](https://developer.chrome.com/docs/extensions/scripting#method-executeScript) directly

There are probably more broken links on this page.

**Comment by jeffposnick** [comment] 2022-03-25 12:59
CC: @sofiayem, @jecfish and @dotproto as this seems like an intersection of Chrome Extensions + DevTools.

**Comment by AaronForinton** [comment] 2022-11-11 00:05
I'm closing this because I've tested the page and found all of the links on it working. I'm assuming any broken links may have been caused by content migration and that it's now resolved.

**Closed by AaronForinton** 2022-11-11 00:05 UTC
Labels: bug, P2, content
