### ISSUE TITLE
The page isn't interactive anymore

### ISSUE THREAD

**Issue by Ljpelletier** [GoogleChrome/developer.chrome.com#616] opened 2021-04-07 21:37 UTC
Hi! The page has lots of activities to do, or had in this case. Do to an update probably, it isn't working properly.

The site is right here:

https://developer.chrome.com/docs/devtools/css/

Thanks!
Luke Pelletier

**Comment by robdodson** [comment] 2021-07-30 01:16
Duplicate of #606

**Closed by robdodson** 2021-07-30 01:16 UTC
Labels: bug
