### ISSUE TITLE
Misisng red box

### ISSUE THREAD

**Issue by LenkaLuz** [GoogleChrome/developer.chrome.com#1034] opened 2021-07-26 07:18 UTC
Hi,

On https://developer.chrome.com/docs/devtools/css/
below the headline
View an element's CSS 
is the red box missing between the point one and two. (the same applies for the tasks below)

BR,
Lenka

**Comment by robdodson** [comment] 2021-07-30 01:16
Duplicate of #606

**Closed by robdodson** 2021-07-30 01:16 UTC
Labels: P2, bug
