### ISSUE TITLE
[docs] chrome.i18n.getMessage(messageName, **substitutions**, options) parameter type incorrect.

### ISSUE THREAD

**Issue by CarsonSlovoka** [GoogleChrome/developer.chrome.com#1234] opened 2021-08-18 16:51 UTC
[method-getMessage](https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage)

> ![image](https://user-images.githubusercontent.com/17170765/129937721-5cf395f2-2cce-4f79-99a8-4d7b8f124e59.png)

I think it should be the ``array`` or ``string``, am I right?

test data

```json5
"bye": {
    "message": "Goodbye, $USER$. Come back to $OUR_SITE$ soon!",
    "description": "Say goodbye to the user",
    "placeholders": {
      "our_site": {
        "content": "$2",
      },
      "user": {
        "content": "$1",
        "example": "Cira"
      }
    }
  }
```

```js
chrome.i18n.getMessage("bye")
chrome.i18n.getMessage("bye", ["Carson", "Example.com"])
chrome.i18n.getMessage("bye", "Carson")
```

**Comment by tophf** [comment] 2021-08-20 06:44
The documentation copies `any` from chomium's source ([link](https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/extensions/api/i18n.json;l=43;drc=9e6f666787ad95e2c987696717982b8374ea6362)) so the problem is in chromium, see [this comment by devlin](https://source.chromium.org/chromium/chromium/src/+/main:extensions/renderer/i18n_hooks_delegate.cc;l=202;drc=784a12a7296f539ea8b38d1ed18d87c77bc953c8):

> // TODO(devlin): We currently just ignore any non-string, non-array values
  // for substitutions, but the type is documented as 'any'. We should either
  // enforce type more heavily, or throw an error here.

**Comment by dstmarthe** [comment] 2023-11-23 03:53
Don't think this will need to be migrated to the new issue tracker, so I will close this.

**Closed by dstmarthe** 2023-11-23 03:53 UTC
Labels: bug, P2, extensions, content

**Comment by tophf** [comment] 2023-11-23 03:56
Ideally it should be filed against Chromium's source bug tracker, see my comment above...
